### ISSUE TITLE
Showing usernames / duels with large amounts of users.

### ISSUE THREAD

**Issue by AKilbo** [indspenceable/bc#56]
Using a drop down list to challenge a specific opponent with a significantly large amount of users seems like a non-ideal way to choose who to fight against. Also being able to see 700 battles may make it difficult to find the ones that you are involved with.

**Comment by indspenceable** [comment]
So the way I'm seeing it:
1 - lobby page
You could enter a username to challenge, or choose to "accept random challenges" or "issue random challenge."
when you challenge someone, you go to the challenge page, where you can choose the settings for that game (do you play with finishers, is it real time, etc).
2 - challenge page
the other person gets a notification, and they can accept or reject that challenge.
3 - on your profile, you can see your games, current and old.
